export const AUTO_TEST_DATA = [
  {icon: require('../../assets/animal1.png'), txt: 1},
  {icon: require('../../assets/animal1.png'), txt: 2},
  {icon: require('../../assets/animal1.png'), txt: 3},
  {icon: require('../../assets/animal1.png'), txt: 4},
  {icon: require('../../assets/animal1.png'), txt: 5},
  {icon: require('../../assets/animal1.png'), txt: 6},
  {icon: require('../../assets/animal1.png'), txt: 7},
  {icon: require('../../assets/animal1.png'), txt: 8},
  {icon: require('../../assets/animal1.png'), txt: 9},
  {icon: require('../../assets/animal1.png'), txt: 10},
  {icon: require('../../assets/animal1.png'), txt: 11},
  {icon: require('../../assets/animal1.png'), txt: 12},
  {icon: require('../../assets/animal1.png'), txt: 13},
  {icon: require('../../assets/animal1.png'), txt: 14},
  {icon: require('../../assets/animal1.png'), txt: 15},
  {icon: require('../../assets/animal1.png'), txt: 16},
  {icon: require('../../assets/animal1.png'), txt: 17},
  {icon: require('../../assets/animal1.png'), txt: 18},
  {icon: require('../../assets/animal1.png'), txt: 19},
  {icon: require('../../assets/animal1.png'), txt: 20},
  {icon: require('../../assets/animal1.png'), txt: 21},
  {icon: require('../../assets/animal1.png'), txt: 22},
  {icon: require('../../assets/animal1.png'), txt: 23},
  {icon: require('../../assets/animal1.png'), txt: 24},
  {icon: require('../../assets/animal1.png'), txt: 25},
  {icon: require('../../assets/animal1.png'), txt: 26},
];
